### ISSUE TITLE
Fix SQL connection to not close after each request

### ISSUE THREAD

**Issue by sianghwee** [SongXueZhi/regs4j#1]
The current implementation of MysqlManager closes the connection after each update and query request. This requires for the connection to be set up every time a request is taking place, and this is causing the process to be very slow. I will fix it by only calling the connect and close at the start and end of the run only. In addition, we can consider using ```PreparedStatement``` instead of ```Statement``` to speed up the process.

**Comment by SongXueZhi** [comment]
In fact, here, I have no idea on a great time that connection need to closed. Keep free to try !
