### ISSUE TITLE
amaembo/streamex checkout issue

### ISSUE THREAD

**Issue by bchenghi** [SongXueZhi/regs4j#11]
For the 3 bugs in amaembo/streamex project, the commits cannot be found.
Below is a screenshot for bug 3. Similar errors are shown for 1 and 2.
![image](https://user-images.githubusercontent.com/57175876/195676622-8b38fb5a-8fba-4770-a108-348f1ac3dce5.png)

**Comment by SongXueZhi** [comment]
Hi @bchenghi, this exception is result from we gave a wrong project full name for this bug.  We had updated this info in our cloud database, you can correct this info in local by use "addthis/stream-lib" instead of "amaembo/streamex". Thanks for your feedback!
